import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { Pool } from 'pg';
import { env } from '#configs/env.js';
import { logger } from '#configs/logger.js';

const pool = new Pool({
    connectionString: env.DATABASE_URL,
});

const db = drizzle(pool);

async function main() {
    logger.info('Running migrations...');

    // This looks for the SQL files generated by drizzle-kit
    await migrate(db, { migrationsFolder: './drizzle' });

    logger.info('Migrations completed!');
    await pool.end();
    process.exit(0);
}

main().catch((err) => {
    logger.error('Migration failed:', err);
    process.exit(1);
});
